//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailInformationAboutWorkout
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Dificulty { get; set; }
        public string Creator { get; set; }
        public Nullable<int> QtyCompletedWorkout { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string ExerciseInWorkout { get; set; }
        public string ExerciseInWorkoutDistinct { get; set; }
    }
}
