//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailInformationAboutTrainer
    {
        public string FIO { get; set; }
        public string Mail { get; set; }
        public string Login { get; set; }
        public Nullable<int> Age { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<decimal> AvgRatingWorkout { get; set; }
        public Nullable<int> QtyCreatedWorkout { get; set; }
        public Nullable<int> QtyNegative { get; set; }
        public string Services { get; set; }
    }
}
