//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class ExerciseWorkout
    {
        public int ID { get; set; }
        public int IDExercise { get; set; }
        public int IDWorkout { get; set; }
        public int Qty { get; set; }

        public virtual Exercise Exercise { get; set; }

        [JsonIgnore]
        public virtual Workout Workout { get; set; }
    }
}
