//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise()
        {
            this.ExerciseWorkout = new HashSet<ExerciseWorkout>();
            this.MuscleTypeExercise = new HashSet<MuscleTypeExercise>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool isQtyInSecond { get; set; }
        public string PathToGif { get; set; }

        public string MuscleTypeName
        {


            get
            {
                try
                {
                    var mte = MuscleTypeExercise.ToList();
                    string result = "";
                    foreach (MuscleTypeExercise i in mte)
                    {
                        result = result + i.MuscleType.Name + ", ";
                    }
                    return result;
                }
                catch
                {
                    return null;
                }
            }
        }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExerciseWorkout> ExerciseWorkout { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<MuscleTypeExercise> MuscleTypeExercise { get; set; }
    }
}
