//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryChange
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public Nullable<int> NewWeitght { get; set; }
        public Nullable<int> NewHeight { get; set; }
        public byte[] ImageFront { get; set; }
        public byte[] ImageSide { get; set; }
        public byte[] ImageBack { get; set; }
        public System.DateTime DataChange { get; set; }
    
        public virtual User User { get; set; }
    }
}
