//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class HistoryWorkoutUser
    {
        public int ID { get; set; }
        public int IDWorkout { get; set; }
        public int IDUser { get; set; }
        public System.DateTime DateWorkout { get; set; }
        public string nameWorkout
        {

            get
            {
                try
                {
                    if (Workout != null)
                    {
                        return Workout.Name;

                    }
                    else
                    {
                        return null;
                    }
                }
                catch
                {
                    return null;
                }
            }
        }
        [JsonIgnore]
        public virtual User User { get; set; }
        [JsonIgnore]
        public virtual Workout Workout { get; set; }
    }
}
