//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeWorkout
    {
        public int IDWorkout { get; set; }
        public int IDUser { get; set; }
        public bool IsLike { get; set; }
    
        public virtual User User { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
