//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class LikeNewsUser
    {
        public int IDNews { get; set; }
        public int IDUser { get; set; }
        public bool IsLike { get; set; }

        [JsonIgnore]
        public virtual News News { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
