//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuscleTypeExercise
    {
        public int IDMuscleTypeExercise { get; set; }
        public int IDMuscleType { get; set; }
        public int IDExercise { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual MuscleType MuscleType { get; set; }
    }
}
