//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsComment
    {
        public int ID { get; set; }
        public int IDNews { get; set; }
        public int IDUser { get; set; }
        public Nullable<System.DateTime> TimeSentComment { get; set; }
        public string Comment { get; set; }
    
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
