//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.LikeNewsUser = new HashSet<LikeNewsUser>();
            this.NewsComment = new HashSet<NewsComment>();
        }

        public int ID { get; set; }
        public int IDUser { get; set; }
        public string Description { get; set; }
        public Nullable<int> IDWorkout { get; set; }
        public byte[] image { get; set; }
        public System.DateTime timeCreate { get; set; }
        public int QtyLike
        {
            get
            {
                if (LikeNewsUser != null)
                {
                    return LikeNewsUser.Count();
                }
                else
                {
                    return 0;
                }
            }
        }
        public int QtyComment
        {
            get
            {
                if (NewsComment != null)
                {
                    return NewsComment.Count(); ;
                }
                else
                {
                    return 0;
                }

            }
        }
        public List<NewsComment> AllComments
        {
            get
            {
                return NewsComment.ToList(); ;
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<LikeNewsUser> LikeNewsUser { get; set; }
        public virtual User User { get; set; }
        public virtual Workout Workout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] public virtual ICollection<NewsComment> NewsComment { get; set; }
    }
}
