//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class ReviewUserTrainer
    {
        public int IDUserTrainer { get; set; }
        public int IDUserReview { get; set; }
        public string Review { get; set; }
        public int Rating { get; set; }

        [JsonIgnore]
        public virtual User User { get; set; }

        public virtual User User1 { get; set; }
    }
}
