//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopNewsForAWeek
    {
        public string FioCreator { get; set; }
        public string Description { get; set; }
        public System.DateTime timeCreate { get; set; }
        public string Name { get; set; }
        public Nullable<int> QtyLikes { get; set; }
        public Nullable<int> QtyComments { get; set; }
    }
}
