//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.HistoryChange = new HashSet<HistoryChange>();
            this.HistoryWorkoutUser = new HashSet<HistoryWorkoutUser>();
            this.LikeNewsUser = new HashSet<LikeNewsUser>();
            this.Message = new HashSet<Message>();
            this.Message1 = new HashSet<Message>();
            this.News = new HashSet<News>();
            this.NewsComment = new HashSet<NewsComment>();
            this.ReviewUserTrainer = new HashSet<ReviewUserTrainer>();
            this.ReviewUserTrainer1 = new HashSet<ReviewUserTrainer>();
            this.Service = new HashSet<Service>();
            this.WorkoutReaction = new HashSet<WorkoutReaction>();
            this.Workout = new HashSet<Workout>();
        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Mail { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
        public int IDGender { get; set; }
        public int Weitght
        {

            get
            {
                try
                {
                    if (HistoryChange.Count != 0)
                    {

                        return (int)HistoryChange.Last().NewWeitght;
                    }
                    else
                    {
                        return 0;
                    }
                }
                catch
                {
                    return 0;
                }



            }

        }
        public int Height
        {
            get
            {
                try
                {
                    if (HistoryChange.Count != 0)
                    {

                        return (int)HistoryChange.Last().NewHeight;
                    }
                    else
                    {
                        return 0;
                    }
                }
                catch
                {
                    return 0;
                }


            }

        }
        public int IDRole { get; set; }
        public System.DateTime Birthday { get; set; }
        public byte[] ImageProfile { get; set; }
        public string Description { get; set; }
        public string DescriptionTrainer { get; set; }

        [JsonIgnore]
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] public virtual ICollection<HistoryChange> HistoryChange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] public virtual ICollection<HistoryWorkoutUser> HistoryWorkoutUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<LikeNewsUser> LikeNewsUser { get; set; }
        [JsonIgnore]
        public virtual ICollection<LikeWorkout> LikeWorkout { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Message> Message1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<NewsComment> NewsComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ReviewUserTrainer> ReviewUserTrainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<ReviewUserTrainer> ReviewUserTrainer1 { get; set; }
        [JsonIgnore] public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Service> Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<WorkoutReaction> WorkoutReaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Workout> Workout { get; set; }
    }
}
