//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;

    public partial class Workout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout()
        {
            this.ExerciseWorkout = new HashSet<ExerciseWorkout>();
            this.HistoryWorkoutUser = new HashSet<HistoryWorkoutUser>();
            this.News = new HashSet<News>();
            this.WorkoutReaction = new HashSet<WorkoutReaction>();
            this.LikeWorkout = new HashSet<LikeWorkout>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public int IDUser { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> IDDificulty { get; set; }
        public int IDWorkoutType { get; set; }
        public int DurationInMin
        {
            get
            {
                var i = (Appdata.Context.getDurationWorkoutInSecProc(ID));

                return (i.FirstOrDefault().Value) / 60;
            }
        }

        public string DificultyName
        {
            get
            {
                switch (IDDificulty)
                {
                    case 1:
                        return "Легкая";
                    case 2:
                        return "Средняя";
                    case 3:
                        return "Сложная";
                    default:
                        return "Ошибка";
                }
            }
        }

        public int QtyExersice
        {
            get
            {
                if (ExerciseWorkout != null)
                {

                    return ExerciseWorkout.Count;
                }
                else
                {
                    return 0;
                }
            }
        }
        public int AvgRating
        {
            get
            {
                if (WorkoutReaction.Count != 0)
                {
                    int sumRating = 0;
                    foreach (WorkoutReaction rw in WorkoutReaction)
                    {
                        sumRating += rw.Rating;
                    }
                    return sumRating / WorkoutReaction.Count();
                }
                else
                {

                    return 0;
                }

            }
        }
        public List<WorkoutReaction> AllWorkoutReaction
        {
            get
            {
                return WorkoutReaction.ToList(); ;
            }
        }
        public List<qtyMuscleInWorkout_Result> qtyMuscleInWorkout
        {


            get
            {
                try
                {

                    return Appdata.Context.qtyMuscleInWorkout(ID).ToList();
                }
                catch
                {
                    return null;
                }
            }
        }

        public virtual ICollection<ExerciseWorkout> ExerciseInWorkout { get; set; }

        [JsonIgnore]
        public virtual Dificulty Dificulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ExerciseWorkout> ExerciseWorkout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<HistoryWorkoutUser> HistoryWorkoutUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<News> News { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutReaction> WorkoutReaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<LikeWorkout> LikeWorkout { get; set; }
        [JsonIgnore]
        public virtual WorkoutType WorkoutType { get; set; }
    }
}
