//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourFitnessServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutReaction
    {
        public int IDWorkout { get; set; }
        public int IDUser { get; set; }
        public System.DateTime TimeSent { get; set; }
        public string Review { get; set; }
        public int Rating { get; set; }
    
        public virtual User User { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
